---
- name: Clone bcbio-nextgen from GitHub
  git:
    repo: "{{ bcbio_repo }}"
    version: "{{ bcbio_branch }}"
    dest: "{{ bcbio_dir }}"

- set_fact: image_name=chapmanb/bcbio-nextgen-devel-work
  when: docker_buildtype == "full"

- set_fact: image_name=chapmanb/bcbio-nextgen-devel
  when: docker_buildtype == "code"

- name: Update code in bcbio docker container
  shell: "bcbio_vm.py devel setup_install"
  register: bcbio_docker_build
  args:
    chdir: "{{ bcbio_dir }}"
  when: docker_buildtype == "code"

- name: Build full bcbio docker container
  shell: "docker build -t {{image_name}} {{bcbio_dir}} >{{bcbio_dir}}/build.log 2>&1"
  args:
    executable: /bin/bash
  register: bcbio_docker_build
  ignore_errors: true
  async: 18000
  poll: 30
  when: docker_buildtype == "full"

- command: "tail -100 {{bcbio_dir}}/build.log"
  register: bcbio_docker_debug
  ignore_errors: true
  when: docker_buildtype == "full"

- debug: var=bcbio_docker_debug.stdout_lines
  when: docker_buildtype == "full"

- name: Create gzipped bcbio docker container
  when: bcbio_docker_build|success
  register: bcbio_docker_gzip
  ignore_errors: true
  shell: "DID=$(docker run -d {{image_name}} /bin/bash) && docker export $DID | gzip -c > {{docker_image}}"
  args:
    chdir: "{{ bcbio_dir }}"
    creates: "{{ docker_image }}"
