---
- name: Clone the codebase
  git:
    repo: https://github.com/chapmanb/bcbio-nextgen.git
    version: master
    dest: "{{ bcbio_dir }}"

- name: Build bcbio_vm docker
  shell: "docker build -t chapmanb/bcbio-nextgen-devel-work ."
  args:
    chdir: "{{ bcbio_dir }}"

- name: Produce gzipped bcbio_vm docker image
  shell: "DID=$(docker run -d chapmanb/bcbio-nextgen-devel-work /bin/bash); docker export $DID | gzip -c > bcbio-nextgen-docker-image.gz"
  args:
    chdir: "{{ bcbio_dir }}"
    creates: bcbio-nextgen-docker-image.gz

- name: Upload gzipped bcbio_vm docker image
  command: >
    gof3r put -p bcbio-nextgen-docker-image.gz -k bcbio-nextgen-docker-image.gz
     -b bcbio_nextgen  -m x-amz-storage-class:REDUCED_REDUNDANCY -m x-amz-acl:public-read
  args:
    chdir: "{{ bcbio_dir }}"