---
- name: Clone bcbio-nextgen from GitHub
  git:
    repo: https://github.com/chapmanb/bcbio-nextgen.git
    version: master
    dest: "{{ bcbio_dir }}"

- set_fact: image_name=chapmanb/bcbio-nextgen-devel-work
  when: docker_buildtype == "full"

- set_fact: image_name=chapmanb/bcbio-nextgen-devel
  when: docker_buildtype == "code"

- set_fact: docker_image=bcbio-nextgen-docker-image.gz

- name: Update code in bcbio docker container
  shell: "bcbio_vm.py devel setup_install"
  register: bcbio_docker_build
  args:
    chdir: "{{ bcbio_dir }}"
  when: docker_buildtype == "code"

- name: Build full bcbio docker container
  shell: "docker build -t {{image_name}} {{bcbio_dir}} >{{bcbio_dir}}/build.log 2>&1"
  args:
    executable: /bin/bash
  register: bcbio_docker_build
  ignore_errors: true
  async: 18000
  poll: 30
  when: docker_buildtype == "full"

- command: "tail -100 {{bcbio_dir}}/build.log"
  register: bcbio_docker_debug
  ignore_errors: true
  when: docker_buildtype == "full"

- debug: var=bcbio_docker_debug.stdout_lines
  when: docker_buildtype == "full"

- name: Create gzipped bcbio docker container
  when: bcbio_docker_build|success
  register: bcbio_docker_gzip
  ignore_errors: true
  shell: "DID=$(docker run -d {{image_name}} /bin/bash) && docker export $DID | gzip -c > {{docker_image}}"
  args:
    chdir: "{{ bcbio_dir }}"
    creates: "{{ docker_image }}"

- name: Upload gzipped bcbio docker container to Amazon S3
  when: bcbio_docker_gzip|success and bcbio_docker_build|success and provider == "aws"
  ignore_errors: true
  shell: >
    gof3r put -p {{ docker_image }} -k {{ docker_image }} -b {{ bcbio_container }} -m x-amz-storage-class:REDUCED_REDUNDANCY -m x-amz-acl:public-read
  args:
    chdir: "{{ bcbio_dir }}"

- name: Upload gzipped bcbio docker container to Microsoft Azure Blob
  when: bcbio_docker_gzip|success and bcbio_docker_build|success and provider == "azure"
  ignore_errors: true
  shell: >
    bcbio_vm.py tools upload azure --file {{ docker_image }} --blob {{ docker_image }} --container {{ bcbio_container }} --account_name {{account_name}}
  args:
    chdir: "{{ bcbio_dir }}"
