---
- name: Clone bcbio-nextgen from GitHub
  git:
    repo: https://github.com/chapmanb/bcbio-nextgen.git
    version: master
    dest: "{{ bcbio_dir }}"

- name: Build bcbio docker container
  shell: "docker build -t chapmanb/bcbio-nextgen-devel-work {{bcbio_dir}} >{{bcbio_dir}}/build.log 2>&1"
  args:
    executable: /bin/bash
  register: bcbio_docker_build
  ignore_errors: true
  async: 18000
  poll: 30

- command: "tail -100 {{bcbio_dir}}/build.log"
  register: bcbio_docker_debug
  ignore_errors: true

- debug: var=bcbio_docker_debug.stdout_lines

- name: Create gzipped bcbio docker container
  when: bcbio_docker_build|success
  register: bcbio_docker_gzip
  ignore_errors: true
  shell: "DID=$(docker run -d chapmanb/bcbio-nextgen-devel-work /bin/bash); docker export $DID | gzip -c > bcbio-nextgen-docker-image.gz"
  args:
    chdir: "{{ bcbio_dir }}"
    creates: bcbio-nextgen-docker-image.gz

- name: Upload gzipped bcbio docker container
  when: bcbio_docker_gzip|success and bcbio_docker_build|success
  ignore_errors: true
  shell: >
    export AWS_ACCESS_KEY_ID={{ lookup('env', 'AWS_ACCESS_KEY_ID') }} &&
    export AWS_SECRET_ACCESS_KEY={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} &&
    ~/bin/gof3r put -p bcbio-nextgen-docker-image.gz -k bcbio-nextgen-docker-image.gz -b {{ bcbio_bucket }} -m x-amz-storage-class:REDUCED_REDUNDANCY -m x-amz-acl:public-read
  args:
    chdir: "{{ bcbio_dir }}"