---
- name: Clone the codebase
  git:
    repo: https://github.com/chapmanb/bcbio-nextgen.git
    version: master
    dest: "{{ bcbio_dir }}"

- name: Build bcbio_vm docker
  shell: "docker build -t chapmanb/bcbio-nextgen-devel-work ."
  args:
    executable: /bin/bash
    chdir: "{{ bcbio_dir }}"
  register: bcbio_docker_build
  ignore_errors: true

- debug: var=bcbio_docker_build.stdout_lines

- name: Produce gzipped bcbio_vm docker image
  when: bcbio_docker_build|success
  register: bcbio_docker_gzip
  ignore_errors: true
  shell: "DID=$(docker run -d chapmanb/bcbio-nextgen-devel-work /bin/bash); docker export $DID | gzip -c > bcbio-nextgen-docker-image.gz"
  args:
    chdir: "{{ bcbio_dir }}"
    creates: bcbio-nextgen-docker-image.gz

- name: Upload gzipped bcbio_vm docker image
  when: bcbio_docker_gzip|success
  ignore_errors: true
  shell: >
    export AWS_ACCESS_KEY_ID = {{ lookup('env', 'AWS_ACCESS_KEY_ID') }} &&
    export AWS_SECRET_ACCESS_KEY = {{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }} &&
    ~/bin/gof3r put -p bcbio-nextgen-docker-image.gz -k bcbio-nextgen-docker-image.gz
     -b {{ bcbio_bucker }}  -m x-amz-storage-class:REDUCED_REDUNDANCY -m x-amz-acl:public-read
  args:
    chdir: "{{ bcbio_dir }}"