package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 11

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen-vm.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - bcbio-nextgen
    - nose
    - six

test:
  imports:
    - bcbiovm.version

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT