---
- name: Docker installation
  hosts: all
  connection: paramiko
  vars:
    docker_mnt_loc: "/mnt"
    docker_mnt_device: "/dev/xvdb"
    docker_configfile: "/etc/default/docker"
  tasks:
    - name: Install docker dependencies
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https

    - name: Add docker apt repo (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      shell: echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
      sudo: True

    - name: Add docker apt key (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
      sudo: True

    - name: Install Docker (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt:
        name: "{{ item }}"
        update_cache: True
      with_items:
        - lxc-docker
        - btrfs-tools
      sudo: True

    - name: Install Docker (rpm)
      when: "'{{ansible_distribution}}' in ['CentOS', 'Amazon']"
      yum:
        name: "{{ item }}"
      with_items:
        - docker
        - btrfs-progs
        - btrfs-progs-devel
      sudo: True

    - name: Check for mounted btrfs filesystem
      shell: mount | grep '{{docker_mnt_loc}} type btrfs'
      ignore_errors: True
      register: btrfs_check
      changed_when: btrfs_check.rc > 0
      sudo: True

    - name: Unmount docker filesystem to prep for btrfs
      mount: name={{docker_mnt_loc}} fstype=btrfs src={{docker_mnt_device}} state=unmounted
      when: btrfs_check.changed
      sudo: True

    - name: Create btrfs filesystem
      filesystem: fstype=btrfs dev={{docker_mnt_device}} force=yes opts="-f"
      when: btrfs_check.changed
      sudo: True

    - name: Mount btrfs filesystem on /mnt
      mount: name={{docker_mnt_loc}} fstype=btrfs src={{docker_mnt_device}} state=mounted
      sudo: True

    - name: Adjust Docker to use btrfs filesystem
      lineinfile:
        dest: '{{docker_configfile}}'
        line: 'DOCKER_OPTS="-s btrfs -g {{docker_mnt_loc}}/docker"'
        regexp: '^DOCKER_OPTS'
      sudo: True

    - name: Add current user to the docker group 
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: True
      sudo: True

    - name: Restart Docker server
      service:
        name: docker
        state: restarted
      sudo: True
