---
- name: Docker installation
  hosts: all
  connection: paramiko
  tasks:
    - name: Add docker apt key (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt_key:
        url: https://get.docker.io/gpg
        state: present
      sudo: True

    - name: Add docker apt repo (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      shell: echo deb https://get.docker.io/ubuntu docker main > /etc/apt/sources.list.d/docker.list
      sudo: True

    - name: Install Docker (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt:
        name: "{{ item }}"
        update_cache: True
      with_items:
        - lxc-docker
        - git
        - pigz
      sudo: True

    - name: Install Docker (rpm)
      when: "'{{ansible_distribution}}' in ['CentOS', 'Amazon']"
      yum:
        name: "{{ item }}"
      with_items:
        - docker
        - git
        - pigz
      sudo: True

    - name: Add current user to the docker group 
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: True
      sudo: True

    - name: Restart Docker server
      service:
        name: docker
        state: restarted
      sudo: True
