---
- name: Docker installation
  hosts: all
  connection: paramiko
  vars:
    docker_configfile: "/etc/default/docker"
  tasks:
    - name: Install docker dependencies
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt:
        name: "{{ item }}"
      with_items:
        - apt-transport-https

    - name: Add docker apt repo (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      shell: echo deb https://apt.dockerproject.org/repo ubuntu-trusty main > /etc/apt/sources.list.d/docker.list
      sudo: True

    - name: Add docker apt key (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
      sudo: True

    - name: Install Docker (deb)
      when: "'{{ansible_distribution}}' in ['Ubuntu', 'Debian']"
      apt:
        name: "{{ item }}"
        update_cache: True
      with_items:
        - docker-engine
      sudo: True

    - name: Add docker yum repo (rpm)
      when: "'{{ansible_distribution}}' in ['CentOS', 'Amazon']"
      shell: curl -sSL https://get.docker.com/ | sh
      sudo: True

    - name: Install Docker (rpm)
      when: "'{{ansible_distribution}}' in ['CentOS', 'Amazon']"
      yum:
        name: "{{ item }}"
        update_cache: True
      with_items:
        - docker-engine
      sudo: True

    - name: Add current user to the docker group 
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: True
      sudo: True

    - name: Restart Docker server
      service:
        name: docker
        state: restarted
      sudo: True