# Create the bcbio_vm docker image locally, pushing to S3
---
- name: Rebuild and update bcbio_vm docker image on S3
  hosts: localhost
  gather_facts: True
  vars:
    bcbio_dir: /tmp/bcbio-nextgen
  roles:
    - gof3r
    - bcbio_vm_build
