# Create the bcbio_vm docker image locally
---
- name: Create the bcbio_vm docker image locally
  hosts: 127.0.0.1
  connection: local
  gather_facts: True
  vars:
    bcbio_dir: /tmp/bcbio-nextgen
  roles:
    - bcbio_vm_build
