- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    region: "{{ aws_region|default('us-east-1') }}"
    security_group: cloudman
    instance_type: t1.micro
    image: ami-018c9568
    docker_user: ubuntu
    bcbio_dir: /tmp/bcbio-nextgen
  tasks:
    - name: Launch instance
      local_action: ec2 key_name={{ keypair }} group={{ security_group }} instance_type={{ instance_type }} image={{ image }} wait=true region={{ region }}
      register: ec2
    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }} port=22 delay=30 timeout=320 state=started
      with_items: ec2.instances
    - name: Get rid of SSH "Are you sure you want to continue connecting (yes/no)?" query
      local_action: command sh -c "ssh-keyscan {{ item.public_ip }} >> $HOME/.ssh/known_hosts"
      with_items: ec2.instances

- name: Rebuild and update bcbio_vm docker instance on S3
  hosts: launched
  gather_facts: True
  roles:
    - docker
    - bcbio_vm_build

- name: Terminate EC2 instance
  hosts: localhost
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      local_action:
        module: ec2
        state: 'absent'
        instance_ids: '{{ ec2.instance_ids }}'