---
- name: Prep gof3r release directory
  file: path='{{ gof3r_tmpdir }}' state=directory

- name: Prep local bin directory
  file: path=~/bin state=directory

- name: Get latest gof3r release
  get_url:
    url: 'https://github.com/rlmcpherson/s3gof3r/releases/download/v{{gof3r_ver}}/gof3r_{{gof3r_ver}}_linux_amd64.tar.gz'
    dest: '{{gof3r_tmpdir}}/gof3r_{{gof3r_ver}}_linux_amd64.tar.gz'

- name: Unpack gof3r release
  command: 'tar -xzvpf gof3r_{{gof3r_ver}}_linux_amd64.tar.gz'
  args:
    chdir: '{{gof3r_tmpdir}}'
    creates: '{{gof3r_tmpdir}}/gof3r_{{gof3r_ver}}_linux_amd64/gof3r'

- name: Install gof3r binary
  command: 'cp {{gof3r_tmpdir}}/gof3r_{{gof3r_ver}}_linux_amd64/gof3r ~/bin'
  args:
    creates: ~/bin/gof3r
