package:
  name: bcbio-nextgen-vm
  version: '0.1.0a'

build:
  number: 0

source:
  git_url: https://github.com/chapmanb/bcbio-nextgen-vm.git

requirements:
  build:
    - python
    - setuptools
    - argparse [py26]
    - future
    - ipython
    #- ipython-cluster-helper
    - nose
    #- progressbar2
    - pyyaml
    - pyzmq
    - requests

  run:
    - python
    - setuptools
    - argparse [py26]
    - future
    - ipython
    #- ipython-cluster-helper
    - nose
    #- progressbar2
    - pyyaml
    - pyzmq
    - requests

test:
  imports:
    - bcbiovm.version

about:
  home: https://github.com/chapmanb/bcbio-nextgen-vm
  license: MIT